### ISSUE TITLE
mros2-esp32 introspection

### ISSUE THREAD

**Issue by LuisYordano** [mROS-base/mros2-esp32#6]
Hi team mros2-esp32.

I am testing the demo: echoback_string, which runs correctly.

-------------------
![echoback_string](https://github.com/mROS-base/mros2-esp32/assets/13818395/4df9d345-dfcc-4272-9180-052b96fd908c)

--------------------

I report the following:

1-Cannot see in the console the node that is currently running: mros2_node.

2-Node and topics cannot be visualized in rqt: /to_linux and /to_stm

3-The data cannot be displayed in the topic monitor.

-------------
![instrospection](https://github.com/mROS-base/mros2-esp32/assets/13818395/8cadd312-de12-4dca-bf1a-db446f317efb)

--------------
![topic_monitor](https://github.com/mROS-base/mros2-esp32/assets/13818395/85623ca0-d8af-4eb1-8271-3a790d06ba17)

--------------

It is correct that this information cannot be displayed, or it is necessary to do some additional configuration?

I thank you in advance for your answer.

**Comment by takasehideki** [comment]
@LuisYordano thank you so much for trying our mros2 world! However, I'm truly sorry for replying so late,,, ;(

1. For node names, we, unfortunately, observe them due to the limitation of embeddedRTPS (RTPS stack used for mROS 2).  Please check the Issue in `mros2` repository (I just created it). https://github.com/mROS-base/mros2/issues/44
2. When you want to operate `echoback_string` on the mros2 device, you need to operate `mros2_echoreply_string` on the ROS 2 host machine. Sorry there is no description in this repository, but you can find the operation as follows (we plan to enrich documentation, or commonize the sample code).
  - https://github.com/mROS-base/mros2-mbed#echoback_string-default
  - https://github.com/mROS-base/mros2-host-examples#mros2_echoreply_string
3. As far as our experience, you can observe the message of topics by the topic monitor. Please operate along with 2.

**Comment by LuisYordano** [comment]
Ok, @takasehideki.
