### ISSUE TITLE
It would be nice to see the ros2 node list. (mros2-esp32 v0.5.0)

### ISSUE THREAD

**Issue by yamati-kz** [mROS-base/mros2-esp32#8]
Only two microcomputers are connected. They are seeed studio xiao esp32c3 and ESP32-S3-DevKitC-1.
There seems to be no problem with pub/sub between two microcomputers.

It would be nice to see the ros2 node list. (mros2-esp32).

![Screenshot from 2023-07-14 17-14-20](https://github.com/mROS-base/mros2-esp32/assets/135952435/e770f155-abb5-4147-94e8-0ac96ed45d67)

Here is the source code outline.
![Screenshot from 2023-07-14 17-14-13](https://github.com/mROS-base/mros2-esp32/assets/135952435/7f2fe018-c881-4cb9-992a-d77f66ad1597)

**Comment by takasehideki** [comment]
@yamati-kz thank you so much for trying our mros2 world! However, I'm truly sorry for replying so late,,, ;(

As you pointed out, it would definitely be great if we could check the mros2 node names by `ros2 node list`. However, as far as we observed, this is not going to be easy to achieve,,, Since this is a limitation of the mROS 2 library, I created Issue in that repository. https://github.com/mROS-base/mros2/issues/44

You may leave this Issue open, as it is a good guide for those who will be trying mros2-esp32.

**Comment by yamati-kz** [comment]
This issue will be closed. I look forward to the future.
Since it is not resolved, refer to this https://github.com/mROS-base/mros2/issues/44.
